<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between align-items-center mb-3"><div></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalAdd"><i class="ti ti-plus icon me-1"></i> Tambah</button></div>
<?php if (session()->getFlashdata('errors')): ?><div class="alert alert-danger"><?php foreach (session()->getFlashdata('errors') as $e): ?><div><?= $e ?></div><?php endforeach; ?></div><?php endif; ?>
<div class="card"><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>#</th><th>Judul</th><th>File</th><th>Ukuran</th><th>Download</th><th width="100">Aksi</th></tr></thead><tbody>
<?php foreach ($items as $i => $item): ?><tr><td><?= $i + 1 ?></td><td class="fw-semibold"><?= esc($item->title) ?></td><td><?= esc($item->file ?? '-') ?></td><td><?= esc($item->file_size ?? '-') ?></td><td><?php if ($item->file): ?><a href="<?= base_url('uploads/downloads/'.$item->file) ?>" class="btn btn-sm btn-icon btn-ghost-primary" target="_blank"><i class="ti ti-download icon"></i></a><?php else: ?>-<?php endif; ?></td><td><button class="btn btn-sm btn-icon btn-ghost-warning" data-bs-toggle="modal" data-bs-target="#modalEdit<?= $item->id ?>"><i class="ti ti-pencil icon"></i></button><a href="/admin/downloads/delete/<?= $item->id ?>" class="btn btn-sm btn-icon btn-ghost-danger" onclick="return confirm('Hapus?')"><i class="ti ti-trash icon"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div>

<?php if (!empty($pager)): ?><div class="mt-3"><?= $pager ?></div><?php endif; ?>

<!-- Modal Add -->
<div class="modal fade" id="modalAdd"><div class="modal-dialog modal-lg"><div class="modal-content"><form action="/admin/downloads/store" method="post" enctype="multipart/form-data"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Download</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Judul</label><input type="text" name="title" class="form-control" required></div><div class="col-md-6"><label class="form-label">Kategori</label><select name="category_id" class="form-select"><?php foreach ($categories as $cat): ?><option value="<?= $cat->id ?>"><?= esc($cat->name) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">File</label><input type="file" name="file" class="form-control"></div><div class="col-12"><label class="form-label">Deskripsi</label><textarea name="description" class="form-control" rows="3"></textarea></div></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Simpan</button></div></form></div></div></div>

<!-- Modal Edit templates -->
<?php foreach ($items as $item): ?>
<div class="modal fade" id="modalEdit<?= $item->id ?>"><div class="modal-dialog modal-lg"><div class="modal-content"><form action="/admin/downloads/update/<?= $item->id ?>" method="post" enctype="multipart/form-data"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit: <?= esc($item->title) ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Judul</label><input type="text" name="title" class="form-control" value="<?= esc($item->title) ?>" required></div><div class="col-md-6"><label class="form-label">Kategori</label><select name="category_id" class="form-select"><?php foreach ($categories as $cat): ?><option value="<?= $cat->id ?>" <?= $item->category_id == $cat->id ? 'selected' : '' ?>><?= esc($cat->name) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">File</label><input type="file" name="file" class="form-control"><?php if ($item->file): ?><small class="text-muted d-block mt-1">Current: <?= $item->file ?></small><?php endif; ?></div><div class="col-12"><label class="form-label">Deskripsi</label><textarea name="description" class="form-control" rows="3"><?= esc($item->description) ?></textarea></div></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Update</button></div></form></div></div></div>
<?php endforeach; ?>
<?= $this->endSection() ?>
