<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between align-items-center mb-3"><div></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalAdd"><i class="ti ti-plus icon me-1"></i> Tambah</button></div>
<?php if (session()->getFlashdata('errors')): ?><div class="alert alert-danger"><?php foreach (session()->getFlashdata('errors') as $e): ?><div><?= $e ?></div><?php endforeach; ?></div><?php endif; ?>
<div class="card"><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>#</th><th>Gambar</th><th>Nama</th><th>Ikon</th><th width="100">Aksi</th></tr></thead><tbody>
<?php foreach ($items as $i => $item): ?><tr><td><?= $i + 1 ?></td><td><?php if ($item->gambar): ?><span class="avatar avatar-sm" style="background-image:url(<?= base_url('uploads/fasilitas/'.$item->gambar) ?>)"></span><?php else: ?><span class="avatar avatar-sm"><?= strtoupper(substr($item->nama,0,1)) ?></span><?php endif; ?></td><td class="fw-semibold"><?= esc($item->nama) ?></td><td><?php if ($item->ikon): ?><i class="ti ti-<?= esc($item->ikon) ?> icon"></i> <?= esc($item->ikon) ?><?php else: ?>-<?php endif; ?></td><td><button class="btn btn-sm btn-icon btn-ghost-warning" data-bs-toggle="modal" data-bs-target="#modalEdit<?= $item->id ?>"><i class="ti ti-pencil icon"></i></button><a href="/admin/fasilitas/delete/<?= $item->id ?>" class="btn btn-sm btn-icon btn-ghost-danger" onclick="return confirm('Hapus?')"><i class="ti ti-trash icon"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div>

<?php if (!empty($pager)): ?><div class="mt-3"><?= $pager ?></div><?php endif; ?>

<!-- Modal Add -->
<div class="modal fade" id="modalAdd"><div class="modal-dialog modal-lg"><div class="modal-content"><form action="/admin/fasilitas/store" method="post" enctype="multipart/form-data"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Fasilitas</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Nama</label><input type="text" name="nama" class="form-control" required></div><div class="col-md-6"><label class="form-label">Ikon (Tabler)</label><input type="text" name="ikon" class="form-control" placeholder="school"></div><div class="col-md-6"><label class="form-label">Gambar</label><input type="file" name="gambar" class="form-control" accept="image/*"></div><div class="col-12"><label class="form-label">Deskripsi</label><textarea name="deskripsi" class="form-control" rows="3"></textarea></div></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Simpan</button></div></form></div></div></div>

<!-- Modal Edit templates -->
<?php foreach ($items as $item): ?>
<div class="modal fade" id="modalEdit<?= $item->id ?>"><div class="modal-dialog modal-lg"><div class="modal-content"><form action="/admin/fasilitas/update/<?= $item->id ?>" method="post" enctype="multipart/form-data"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit: <?= esc($item->nama) ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Nama</label><input type="text" name="nama" class="form-control" value="<?= esc($item->nama) ?>" required></div><div class="col-md-6"><label class="form-label">Ikon (Tabler)</label><input type="text" name="ikon" class="form-control" value="<?= esc($item->ikon) ?>" placeholder="school"></div><div class="col-md-6"><label class="form-label">Gambar</label><input type="file" name="gambar" class="form-control" accept="image/*"><?php if ($item->gambar): ?><small class="text-muted d-block mt-1">Current: <?= $item->gambar ?></small><?php endif; ?></div><div class="col-12"><label class="form-label">Deskripsi</label><textarea name="deskripsi" class="form-control" rows="3"><?= esc($item->deskripsi) ?></textarea></div></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Update</button></div></form></div></div></div>
<?php endforeach; ?>
<?= $this->endSection() ?>
