<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between align-items-center mb-3"><div></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalAdd"><i class="ti ti-plus icon me-1"></i> Tambah</button></div>
<?php if (session()->getFlashdata('errors')): ?><div class="alert alert-danger"><?php foreach (session()->getFlashdata('errors') as $e): ?><div><?= $e ?></div><?php endforeach; ?></div><?php endif; ?>
<?php if (session()->getFlashdata('success')): ?><div class="alert alert-success"><?= session()->getFlashdata('success') ?></div><?php endif; ?>

<div class="card"><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>#</th><th>Ikon</th><th>Kode</th><th>Nama Jurusan</th><th>Singkatan</th><th>Kaprodi</th><th>Status</th><th width="100">Aksi</th></tr></thead><tbody>
<?php foreach ($items as $i => $item): ?><tr><td><?= $i + 1 ?></td><td><?php if ($item->ikon): ?><i class="ti ti-<?= esc($item->ikon) ?> icon icon-lg"></i><?php else: ?>-<?php endif; ?></td><td><?= esc($item->kode ?? '-') ?></td><td class="fw-semibold"><?= esc($item->nama) ?></td><td><?= esc($item->singkatan ?? '-') ?></td><td><?= esc($item->kaprodi ?? '-') ?></td><td><?= $item->is_active ? '<span class="badge bg-success">Aktif</span>' : '<span class="badge bg-danger">Nonaktif</span>' ?></td><td><button class="btn btn-sm btn-icon btn-ghost-warning" data-bs-toggle="modal" data-bs-target="#modalEdit<?= $item->id ?>"><i class="ti ti-pencil icon"></i></button><a href="/admin/jurusan/delete/<?= $item->id ?>" class="btn btn-sm btn-icon btn-ghost-danger" onclick="return confirm('Hapus?')"><i class="ti ti-trash icon"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div>

<?php if (!empty($pager)): ?><div class="mt-3"><?= $pager ?></div><?php endif; ?>

<!-- Modal Add -->
<div class="modal fade" id="modalAdd"><div class="modal-dialog modal-lg"><div class="modal-content"><form action="/admin/jurusan/store" method="post" enctype="multipart/form-data"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Jurusan</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Kode</label><input type="text" name="kode" class="form-control"></div><div class="col-md-6"><label class="form-label">Nama Jurusan</label><input type="text" name="nama" class="form-control" required></div><div class="col-md-6"><label class="form-label">Singkatan</label><input type="text" name="singkatan" class="form-control"></div><div class="col-md-6"><label class="form-label">Kaprodi</label><input type="text" name="kaprodi" class="form-control"></div><div class="col-md-6"><label class="form-label">Ikon (Tabler)</label><input type="text" name="ikon" class="form-control" placeholder="code"></div><div class="col-md-6"><label class="form-label">Foto</label><input type="file" name="foto" class="form-control" accept="image/*"></div><div class="col-12"><label class="form-label">Deskripsi</label><textarea name="deskripsi" class="form-control" rows="4"></textarea></div><div class="col-12"><label class="form-label">Prospek Karir</label><textarea name="prospek_karir" class="form-control" rows="3"></textarea></div><div class="col-md-6"><label class="form-label">Akreditasi</label><input type="text" name="akreditasi" class="form-control"></div><div class="col-md-3"><label class="form-label">Sort</label><input type="number" name="sort_order" class="form-control" value="0"></div><div class="col-md-3 d-flex align-items-end pb-2"><label class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked><span class="form-check-label">Aktif</span></label></div></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Simpan</button></div></form></div></div></div>

<!-- Modal Edit templates -->
<?php foreach ($items as $item): ?>
<div class="modal fade" id="modalEdit<?= $item->id ?>"><div class="modal-dialog modal-lg"><div class="modal-content"><form action="/admin/jurusan/update/<?= $item->id ?>" method="post" enctype="multipart/form-data"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit: <?= esc($item->nama) ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Kode</label><input type="text" name="kode" class="form-control" value="<?= esc($item->kode) ?>"></div><div class="col-md-6"><label class="form-label">Nama Jurusan</label><input type="text" name="nama" class="form-control" value="<?= esc($item->nama) ?>" required></div><div class="col-md-6"><label class="form-label">Singkatan</label><input type="text" name="singkatan" class="form-control" value="<?= esc($item->singkatan) ?>"></div><div class="col-md-6"><label class="form-label">Kaprodi</label><input type="text" name="kaprodi" class="form-control" value="<?= esc($item->kaprodi) ?>"></div><div class="col-md-6"><label class="form-label">Ikon (Tabler)</label><input type="text" name="ikon" class="form-control" value="<?= esc($item->ikon) ?>" placeholder="code"></div><div class="col-md-6"><label class="form-label">Foto</label><input type="file" name="foto" class="form-control" accept="image/*"><?php if ($item->foto): ?><small class="text-muted d-block mt-1">Current: <?= $item->foto ?></small><?php endif; ?></div><div class="col-12"><label class="form-label">Deskripsi</label><textarea name="deskripsi" class="form-control" rows="4"><?= esc($item->deskripsi) ?></textarea></div><div class="col-12"><label class="form-label">Prospek Karir</label><textarea name="prospek_karir" class="form-control" rows="3"><?= esc($item->prospek_karir) ?></textarea></div><div class="col-md-6"><label class="form-label">Akreditasi</label><input type="text" name="akreditasi" class="form-control" value="<?= esc($item->akreditasi) ?>"></div><div class="col-md-3"><label class="form-label">Sort</label><input type="number" name="sort_order" class="form-control" value="<?= $item->sort_order ?>"></div><div class="col-md-3 d-flex align-items-end pb-2"><label class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_active" value="1" <?= $item->is_active ? 'checked' : '' ?>><span class="form-check-label">Aktif</span></label></div></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Update</button></div></form></div></div></div>
<?php endforeach; ?>
<?= $this->endSection() ?>
