<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between align-items-center mb-3"><div></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalAdd"><i class="ti ti-plus icon me-1"></i> Tambah</button></div>
<?php if (session()->getFlashdata('errors')): ?><div class="alert alert-danger"><?php foreach (session()->getFlashdata('errors') as $e): ?><div><?= $e ?></div><?php endforeach; ?></div><?php endif; ?>
<?php if (session()->getFlashdata('success')): ?><div class="alert alert-success"><?= session()->getFlashdata('success') ?></div><?php endif; ?>

<div class="card"><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>#</th><th>Nama Album</th><th>Slug</th><th>Cover</th><th>Foto</th><th width="100">Aksi</th></tr></thead><tbody>
<?php foreach ($items as $i => $item): ?><tr><td><?= $i + 1 ?></td><td class="fw-semibold"><?= esc($item->name) ?></td><td><?= esc($item->slug ?? '-') ?></td><td><?php if ($item->cover): ?><span class="avatar avatar-sm" style="background-image:url(<?= base_url('uploads/gallery/'.$item->cover) ?>)"></span><?php else: ?>-<?php endif; ?></td><td><?= $item->photo_count ?? 0 ?></td><td><button class="btn btn-sm btn-icon btn-ghost-warning" data-bs-toggle="modal" data-bs-target="#modalEdit<?= $item->id ?>"><i class="ti ti-pencil icon"></i></button><a href="/admin/gallery/albums/delete/<?= $item->id ?>" class="btn btn-sm btn-icon btn-ghost-danger" onclick="return confirm('Hapus?')"><i class="ti ti-trash icon"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div>

<?php if (!empty($pager)): ?><div class="mt-3"><?= $pager ?></div><?php endif; ?>

<!-- Modal Add -->
<div class="modal fade" id="modalAdd"><div class="modal-dialog"><div class="modal-content"><form action="/admin/gallery/albums/store" method="post" enctype="multipart/form-data"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Album</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Nama Album</label><input type="text" name="name" class="form-control" required></div><div class="mb-3"><label class="form-label">Slug</label><input type="text" name="slug" class="form-control"></div><div class="mb-3"><label class="form-label">Cover</label><input type="file" name="cover" class="form-control" accept="image/*"></div><div class="mb-3"><label class="form-label">Deskripsi</label><textarea name="description" class="form-control" rows="3"></textarea></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Simpan</button></div></form></div></div></div>

<!-- Modal Edit templates -->
<?php foreach ($items as $item): ?>
<div class="modal fade" id="modalEdit<?= $item->id ?>"><div class="modal-dialog"><div class="modal-content"><form action="/admin/gallery/albums/update/<?= $item->id ?>" method="post" enctype="multipart/form-data"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit: <?= esc($item->name) ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Nama Album</label><input type="text" name="name" class="form-control" value="<?= esc($item->name) ?>" required></div><div class="mb-3"><label class="form-label">Slug</label><input type="text" name="slug" class="form-control" value="<?= esc($item->slug) ?>"></div><div class="mb-3"><label class="form-label">Cover</label><input type="file" name="cover" class="form-control" accept="image/*"><?php if ($item->cover): ?><small class="text-muted d-block mt-1">Current: <?= $item->cover ?></small><?php endif; ?></div><div class="mb-3"><label class="form-label">Deskripsi</label><textarea name="description" class="form-control" rows="3"><?= esc($item->description) ?></textarea></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Update</button></div></form></div></div></div>
<?php endforeach; ?>
<?= $this->endSection() ?>
