<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between align-items-center mb-3"><div></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalAdd"><i class="ti ti-plus icon me-1"></i> Tambah</button></div>
<?php if (session()->getFlashdata('errors')): ?><div class="alert alert-danger"><?php foreach (session()->getFlashdata('errors') as $e): ?><div><?= $e ?></div><?php endforeach; ?></div><?php endif; ?>
<div class="card"><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>#</th><th>Title</th><th>URL</th><th width="100">Aksi</th></tr></thead><tbody>
<?php foreach ($items as $i => $item): ?><tr><td><?= $i + 1 ?></td><td class="fw-semibold"><?= esc($item->title) ?></td><td><?php if ($item->url): ?><a href="<?= esc($item->url) ?>" target="_blank" class="text-muted text-truncate d-inline-block" style="max-width:250px"><?= esc($item->url) ?></a><?php else: ?>-<?php endif; ?></td><td><button class="btn btn-sm btn-icon btn-ghost-warning" data-bs-toggle="modal" data-bs-target="#modalEdit<?= $item->id ?>"><i class="ti ti-pencil icon"></i></button><a href="/admin/videos/delete/<?= $item->id ?>" class="btn btn-sm btn-icon btn-ghost-danger" onclick="return confirm('Hapus?')"><i class="ti ti-trash icon"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div>

<?php if (!empty($pager)): ?><div class="mt-3"><?= $pager ?></div><?php endif; ?>

<!-- Modal Add -->
<div class="modal fade" id="modalAdd"><div class="modal-dialog modal-lg"><div class="modal-content"><form action="/admin/videos/store" method="post" enctype="multipart/form-data"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Video</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Title</label><input type="text" name="title" class="form-control" required></div><div class="col-md-6"><label class="form-label">URL</label><input type="url" name="url" class="form-control"></div><div class="col-md-6"><label class="form-label">Thumbnail</label><input type="file" name="thumbnail" class="form-control" accept="image/*"></div><div class="col-12"><label class="form-label">Embed Code</label><textarea name="embed_code" class="form-control" rows="4" placeholder="<iframe ...></iframe>"></textarea></div></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Simpan</button></div></form></div></div></div>

<!-- Modal Edit templates -->
<?php foreach ($items as $item): ?>
<div class="modal fade" id="modalEdit<?= $item->id ?>"><div class="modal-dialog modal-lg"><div class="modal-content"><form action="/admin/videos/update/<?= $item->id ?>" method="post" enctype="multipart/form-data"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit: <?= esc($item->title) ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Title</label><input type="text" name="title" class="form-control" value="<?= esc($item->title) ?>" required></div><div class="col-md-6"><label class="form-label">URL</label><input type="url" name="url" class="form-control" value="<?= esc($item->url) ?>"></div><div class="col-md-6"><label class="form-label">Thumbnail</label><input type="file" name="thumbnail" class="form-control" accept="image/*"><?php if ($item->thumbnail): ?><small class="text-muted d-block mt-1">Current: <?= $item->thumbnail ?></small><?php endif; ?></div><div class="col-12"><label class="form-label">Embed Code</label><textarea name="embed_code" class="form-control" rows="4" placeholder="<iframe ...></iframe>"><?= esc($item->embed_code) ?></textarea></div></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Update</button></div></form></div></div></div>
<?php endforeach; ?>
<?= $this->endSection() ?>
