<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><a href="/admin/menus" class="btn btn-ghost-secondary"><i class="ti ti-arrow-left icon me-1"></i> Kembali</a></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalAdd"><i class="ti ti-plus icon me-1"></i> Tambah Item</button></div>
<?php if (session()->getFlashdata('errors')): ?><div class="alert alert-danger"><?php foreach (session()->getFlashdata('errors') as $e): ?><div><?= $e ?></div><?php endforeach; ?></div><?php endif; ?>
<?php if (session()->getFlashdata('success')): ?><div class="alert alert-success"><?= session()->getFlashdata('success') ?></div><?php endif; ?>

<h4 class="mb-3">Menu: <?= esc($menu->name) ?></h4>

<div class="card"><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>#</th><th>Label</th><th>URL</th><th>Target</th><th>Parent</th><th>Sort</th><th>Status</th><th width="100">Aksi</th></tr></thead><tbody>
<?php foreach ($items as $i => $item): ?><tr><td><?= $i + 1 ?></td><td class="fw-semibold"><?= esc($item->label) ?></td><td><code class="text-muted"><?= esc($item->url ?? '-') ?></code></td><td><?= esc($item->target ?? '_self') ?></td><td><?= esc($item->parent_label ?? '-') ?></td><td><?= $item->sort_order ?></td><td><?= $item->is_active ? '<span class="badge bg-success">Aktif</span>' : '<span class="badge bg-danger">Nonaktif</span>' ?></td><td><button class="btn btn-sm btn-icon btn-ghost-warning" data-bs-toggle="modal" data-bs-target="#modalEdit<?= $item->id ?>"><i class="ti ti-pencil icon"></i></button><a href="/admin/menus/items/delete/<?= $item->id ?>" class="btn btn-sm btn-icon btn-ghost-danger" onclick="return confirm('Hapus?')"><i class="ti ti-trash icon"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div>

<?php if (!empty($pager)): ?><div class="mt-3"><?= $pager ?></div><?php endif; ?>

<!-- Modal Add -->
<div class="modal fade" id="modalAdd"><div class="modal-dialog"><div class="modal-content"><form action="/admin/menus/items/store/<?= $menu->id ?>" method="post"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Menu Item</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Label</label><input type="text" name="label" class="form-control" required></div><div class="mb-3"><label class="form-label">URL</label><input type="text" name="url" class="form-control" placeholder="/halaman, https://..."></div><div class="mb-3"><label class="form-label">Target</label><select name="target" class="form-select"><option value="_self">_self</option><option value="_blank">_blank</option></select></div><div class="mb-3"><label class="form-label">Parent</label><select name="parent_id" class="form-select"><option value="">-- Tidak ada --</option><?php foreach ($items as $parentItem): ?><option value="<?= $parentItem->id ?>"><?= esc($parentItem->label) ?></option><?php endforeach; ?></select></div><div class="mb-3"><label class="form-label">Icon (Tabler)</label><input type="text" name="icon" class="form-control" placeholder="home"></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Sort</label><input type="number" name="sort_order" class="form-control" value="0"></div><div class="col-md-6 d-flex align-items-end pb-2"><label class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked><span class="form-check-label">Aktif</span></label></div></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Simpan</button></div></form></div></div></div>

<!-- Modal Edit templates -->
<?php foreach ($items as $item): ?>
<div class="modal fade" id="modalEdit<?= $item->id ?>"><div class="modal-dialog"><div class="modal-content"><form action="/admin/menus/items/update/<?= $item->id ?>" method="post"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit: <?= esc($item->label) ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Label</label><input type="text" name="label" class="form-control" value="<?= esc($item->label) ?>" required></div><div class="mb-3"><label class="form-label">URL</label><input type="text" name="url" class="form-control" value="<?= esc($item->url) ?>" placeholder="/halaman, https://..."></div><div class="mb-3"><label class="form-label">Target</label><select name="target" class="form-select"><option value="_self" <?= $item->target == '_self' ? 'selected' : '' ?>>_self</option><option value="_blank" <?= $item->target == '_blank' ? 'selected' : '' ?>>_blank</option></select></div><div class="mb-3"><label class="form-label">Parent</label><select name="parent_id" class="form-select"><option value="">-- Tidak ada --</option><?php foreach ($allItems as $parentItem): ?><?php if ($parentItem->id != $item->id): ?><option value="<?= $parentItem->id ?>" <?= $item->parent_id == $parentItem->id ? 'selected' : '' ?>><?= esc($parentItem->label) ?></option><?php endif; ?><?php endforeach; ?></select></div><div class="mb-3"><label class="form-label">Icon (Tabler)</label><input type="text" name="icon" class="form-control" value="<?= esc($item->icon) ?>" placeholder="home"></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Sort</label><input type="number" name="sort_order" class="form-control" value="<?= $item->sort_order ?>"></div><div class="col-md-6 d-flex align-items-end pb-2"><label class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_active" value="1" <?= $item->is_active ? 'checked' : '' ?>><span class="form-check-label">Aktif</span></label></div></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Update</button></div></form></div></div></div>
<?php endforeach; ?>
<?= $this->endSection() ?>
